In [27]:
import pandas as pd
import numpy as np
from scipy.stats import f_oneway, chi2_contingency
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Phase 4: Statistical Testing & Feature Selection
Conducting statistical tests (SciPy) like t-tests/ANOVA to validate feature significance against the target variable, followed by dimensionality reduction (PCA) if necessary, to finalize the ML-ready dataset.

In [28]:
feature_df  = pd.read_csv('../data/processed/engineered_market_data.csv')

In [29]:
feature_df.head()

,Date,Close,High,Low,Open,Volume,Target,RSI,Doji,Bullish_Engulfing,...,EMA_26,MACD,MACD_Signal,Ticker_Name_INFY.NS,Ticker_Name_ITC.NS,Ticker_Name_LT.NS,Ticker_Name_RELIANCE.NS,Ticker_Name_TCS.NS,Ticker_Name_^NSEBANK,Ticker_Name_^NSEI
0,2016-06-14,8108.850098,8134.950195,8069.500000,8134.399902,145500,1,0.000000,0,0,...,8110.470468,-0.139601,-0.027920,0,0,0,0,0,0,1
1,2016-06-15,8206.599609,8213.200195,8123.149902,8139.399902,169800,0,81.120255,0,0,...,8117.591145,7.550297,1.487723,0,0,0,0,0,0,1
2,2016-06-16,8140.750000,8180.649902,8074.450195,8180.649902,189200,1,51.066938,0,0,...,8119.306616,8.236143,2.837407,0,0,0,0,0,0,1
3,2016-06-17,8170.200195,8195.250000,8135.799805,8176.649902,166600,1,58.476271,0,0,...,8123.076511,11.028931,4.475712,0,0,0,0,0,0,1
4,2016-06-20,8238.500000,8244.150391,8107.350098,8115.750000,168600,0,69.870494,0,1,...,8131.626399,18.539744,7.288518,0,0,0,0,0,0,1

In [30]:
selected_df = feature_df.copy()

In [31]:
selected_df.head()

,Date,Close,High,Low,Open,Volume,Target,RSI,Doji,Bullish_Engulfing,...,EMA_26,MACD,MACD_Signal,Ticker_Name_INFY.NS,Ticker_Name_ITC.NS,Ticker_Name_LT.NS,Ticker_Name_RELIANCE.NS,Ticker_Name_TCS.NS,Ticker_Name_^NSEBANK,Ticker_Name_^NSEI
0,2016-06-14,8108.850098,8134.950195,8069.500000,8134.399902,145500,1,0.000000,0,0,...,8110.470468,-0.139601,-0.027920,0,0,0,0,0,0,1
1,2016-06-15,8206.599609,8213.200195,8123.149902,8139.399902,169800,0,81.120255,0,0,...,8117.591145,7.550297,1.487723,0,0,0,0,0,0,1
2,2016-06-16,8140.750000,8180.649902,8074.450195,8180.649902,189200,1,51.066938,0,0,...,8119.306616,8.236143,2.837407,0,0,0,0,0,0,1
3,2016-06-17,8170.200195,8195.250000,8135.799805,8176.649902,166600,1,58.476271,0,0,...,8123.076511,11.028931,4.475712,0,0,0,0,0,0,1
4,2016-06-20,8238.500000,8244.150391,8107.350098,8115.750000,168600,0,69.870494,0,1,...,8131.626399,18.539744,7.288518,0,0,0,0,0,0,1

In [32]:
selected_df.set_index('Date', inplace= True)

In [33]:
X = selected_df.drop('Target', axis= 1)

In [34]:
X.head()

,Close,High,Low,Open,Volume,RSI,Doji,Bullish_Engulfing,Bearish_Engulfing,Hammer,...,EMA_26,MACD,MACD_Signal,Ticker_Name_INFY.NS,Ticker_Name_ITC.NS,Ticker_Name_LT.NS,Ticker_Name_RELIANCE.NS,Ticker_Name_TCS.NS,Ticker_Name_^NSEBANK,Ticker_Name_^NSEI
Date,,,,,,,,,,,,,,,,,,,,,
2016-06-14,8108.850098,8134.950195,8069.500000,8134.399902,145500,0.000000,0,0,0,0,...,8110.470468,-0.139601,-0.027920,0,0,0,0,0,0,1
2016-06-15,8206.599609,8213.200195,8123.149902,8139.399902,169800,81.120255,0,0,0,0,...,8117.591145,7.550297,1.487723,0,0,0,0,0,0,1
2016-06-16,8140.750000,8180.649902,8074.450195,8180.649902,189200,51.066938,0,0,0,0,...,8119.306616,8.236143,2.837407,0,0,0,0,0,0,1
2016-06-17,8170.200195,8195.250000,8135.799805,8176.649902,166600,58.476271,0,0,0,0,...,8123.076511,11.028931,4.475712,0,0,0,0,0,0,1
2016-06-20,8238.500000,8244.150391,8107.350098,8115.750000,168600,69.870494,0,1,0,0,...,8131.626399,18.539744,7.288518,0,0,0,0,0,0,1

In [35]:
y = selected_df['Target']

In [36]:
y.head()

Date
2016-06-14    1
2016-06-15    0
2016-06-16    1
2016-06-17    1
2016-06-20    0
Name: Target, dtype: int64

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, shuffle= False)

In [38]:
X_train.shape

(15795, 21)

In [39]:
X_test.shape

(3949, 21)

In [40]:
y_train.shape

(15795,)

In [41]:
y_test.shape

(3949,)

In [42]:
X_test.columns

Index(['Close', 'High', 'Low', 'Open', 'Volume', 'RSI', 'Doji',
       'Bullish_Engulfing', 'Bearish_Engulfing', 'Hammer', 'EMA_12', 'EMA_26',
       'MACD', 'MACD_Signal', 'Ticker_Name_INFY.NS', 'Ticker_Name_ITC.NS',
       'Ticker_Name_LT.NS', 'Ticker_Name_RELIANCE.NS', 'Ticker_Name_TCS.NS',
       'Ticker_Name_^NSEBANK', 'Ticker_Name_^NSEI'],
      dtype='str')

In [43]:
test_columns = ['Close', 'High', 'Low', 'Open', 'Volume', 'RSI', 'Doji','Bullish_Engulfing', 'Bearish_Engulfing', 'Hammer',
           'Ticker_Name_INFY.NS', 'Ticker_Name_ITC.NS', 'Ticker_Name_LT.NS','Ticker_Name_RELIANCE.NS', 'Ticker_Name_TCS.NS',
           'Ticker_Name_^NSEBANK','Ticker_Name_^NSEI']

In [44]:
f_oneway_result: list = []

In [45]:
significant_value = 0.05

for column in test_columns:
     group_0 = X_train[column][y_train == 0]
     group_1 = X_train[column][y_train == 1]
     f_stats_value , p_value = f_oneway(group_0, group_1)
     result = 'H0 REJECT' if p_value < significant_value else 'H0 FAIL TO REJECT'
     f_oneway_test: dict = {
          'feature'           : column,
          'f_stats_value'     : f_stats_value,
          'p_value'           : p_value,
          'result'            : result
     }

     f_oneway_result.append(f_oneway_test)

In [46]:
f_oneway_result_df = pd.DataFrame(f_oneway_result)

In [47]:
f_oneway_result_df

                    feature  f_stats_value   p_value             result
0                     Close       3.193492  0.073951  H0 FAIL TO REJECT
1                      High       3.211921  0.073123  H0 FAIL TO REJECT
2                       Low       3.146962  0.076088  H0 FAIL TO REJECT
3                      Open       3.177218  0.074691  H0 FAIL TO REJECT
4                    Volume       0.014505  0.904140  H0 FAIL TO REJECT
5                       RSI       0.001927  0.964989  H0 FAIL TO REJECT
6                      Doji       3.515453  0.060817  H0 FAIL TO REJECT
7         Bullish_Engulfing       2.660281  0.102902  H0 FAIL TO REJECT
8         Bearish_Engulfing       0.221414  0.637971  H0 FAIL TO REJECT
9                    Hammer       0.074781  0.784502  H0 FAIL TO REJECT
10      Ticker_Name_INFY.NS       0.316674  0.573621  H0 FAIL TO REJECT
11       Ticker_Name_ITC.NS       5.681356  0.017158          H0 REJECT
12        Ticker_Name_LT.NS            NaN       NaN  H0 FAIL TO REJECT
13  Ticker_Name_RELIANCE.NS       0.065453  0.798080  H0 FAIL TO REJECT
14       Ticker_Name_TCS.NS       2.468753  0.116150  H0 FAIL TO REJECT
15     Ticker_Name_^NSEBANK       3.696469  0.054546  H0 FAIL TO REJECT
16        Ticker_Name_^NSEI       5.383608  0.020339          H0 REJECT

In [48]:
rf_model = RandomForestClassifier(random_state= 42)

In [49]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [50]:
feature_importances = rf_model.feature_importances_
feature_importances

array([0.09064171, 0.09035545, 0.09006268, 0.09004958, 0.10300466,
       0.10779096, 0.00854648, 0.00415333, 0.00547196, 0.0057402 ,
       0.08986901, 0.09072963, 0.10654632, 0.10551916, 0.00378324,
       0.0003708 , 0.        , 0.00398296, 0.00171867, 0.00076222,
       0.00090098])

In [51]:
feature_importances_df = pd.DataFrame(feature_importances.reshape(1,21), columns= X_train.columns)
feature_importances_df

,Close,High,Low,Open,Volume,RSI,Doji,Bullish_Engulfing,Bearish_Engulfing,Hammer,...,EMA_26,MACD,MACD_Signal,Ticker_Name_INFY.NS,Ticker_Name_ITC.NS,Ticker_Name_LT.NS,Ticker_Name_RELIANCE.NS,Ticker_Name_TCS.NS,Ticker_Name_^NSEBANK,Ticker_Name_^NSEI
0,0.090642,0.090355,0.090063,0.09005,0.103005,0.107791,0.008546,0.004153,0.005472,0.00574,...,0.09073,0.106546,0.105519,0.003783,0.000371,0.0,0.003983,0.001719,0.000762,0.000901

In [52]:
X_test.columns

Index(['Close', 'High', 'Low', 'Open', 'Volume', 'RSI', 'Doji',
       'Bullish_Engulfing', 'Bearish_Engulfing', 'Hammer', 'EMA_12', 'EMA_26',
       'MACD', 'MACD_Signal', 'Ticker_Name_INFY.NS', 'Ticker_Name_ITC.NS',
       'Ticker_Name_LT.NS', 'Ticker_Name_RELIANCE.NS', 'Ticker_Name_TCS.NS',
       'Ticker_Name_^NSEBANK', 'Ticker_Name_^NSEI'],
      dtype='str')

In [53]:
column_to_drop = [col for col in X_test.columns if 'Ticker_Name' in col]
column_to_drop

['Ticker_Name_INFY.NS',
 'Ticker_Name_ITC.NS',
 'Ticker_Name_LT.NS',
 'Ticker_Name_RELIANCE.NS',
 'Ticker_Name_TCS.NS',
 'Ticker_Name_^NSEBANK',
 'Ticker_Name_^NSEI']

In [54]:
selected_df.drop(column_to_drop, axis= 1, inplace= True)

In [55]:
selected_df.head()

,Close,High,Low,Open,Volume,Target,RSI,Doji,Bullish_Engulfing,Bearish_Engulfing,Hammer,EMA_12,EMA_26,MACD,MACD_Signal
Date,,,,,,,,,,,,,,,
2016-06-14,8108.850098,8134.950195,8069.500000,8134.399902,145500,1,0.000000,0,0,0,0,8110.330867,8110.470468,-0.139601,-0.027920
2016-06-15,8206.599609,8213.200195,8123.149902,8139.399902,169800,0,81.120255,0,0,0,0,8125.141443,8117.591145,7.550297,1.487723
2016-06-16,8140.750000,8180.649902,8074.450195,8180.649902,189200,1,51.066938,0,0,0,0,8127.542759,8119.306616,8.236143,2.837407
2016-06-17,8170.200195,8195.250000,8135.799805,8176.649902,166600,1,58.476271,0,0,0,0,8134.105442,8123.076511,11.028931,4.475712
2016-06-20,8238.500000,8244.150391,8107.350098,8115.750000,168600,0,69.870494,0,1,0,0,8150.166143,8131.626399,18.539744,7.288518

In [56]:
selected_df.to_csv('../data/processed/selected_features.csv', index= True)